---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      resources:
        requests:
          cpu: 200m
          memory: 64M
        limits:
          cpu: 500m
          memory: 128M

