---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: webserver
spec:
  containers:
    - name: httpd
      image: httpd
  tolerations:
    - key: slave2
      operator: Equal
      effect: NoSchedule
      value: intelliqit2
